#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.dirname(__FILE__) + "/../lib"))

require "ruby_maze"

size = ARGV[0]

begin
  raise(ArgumentError, "Usage: ruby-maze [maze size]") unless size
  raise(ArgumentError, "The [maze size] must be more than 3") if size.to_i < 3
  RubyMaze.new(size.to_i).run
rescue ArgumentError => e
  puts e.message
end
